# Generated by Django 5.2 on 2025-05-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('ADMIN', 'Administrator'), ('PRAWNIK', 'Radca prawny'), ('POMOC', 'Pomoc administracyjna'), ('RADA_ZARZAD', 'Zarząd Rady Dyscypliny')], max_length=50, unique=True, verbose_name='Nazwa uprawnienia')),
            ],
            options={
                'verbose_name': 'Uprawnienie',
                'verbose_name_plural': 'Uprawnienia',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email (login)')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Dostęp do admina Django')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data dołączenia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('osoba', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konto_uzytkownika', to='core.osoba', verbose_name='Dane Osobowe')),
                ('rd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzytkownicy', to='core.rd', verbose_name='Rada Dyscypliny')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('uprawnienia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uzytkownicy', to='users.uprawnienia', verbose_name='Uprawnienia')),
            ],
            options={
                'verbose_name': 'Użytkownik Systemu',
                'verbose_name_plural': 'Użytkownicy Systemu',
            },
        ),
    ]
