# Generated by Django 5.2 on 2025-04-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PRAWNIK', 'Prawnik'), ('OBSLUGA', 'Obsługa'), ('RADA', 'Rada')], max_length=10),
        ),
    ]
