# Generated by Django 5.2 on 2025-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rada_wydzialu',
            field=models.CharField(blank=True, default='Wydział Elektrotechniki i Informatyki', max_length=255, verbose_name='Rada/Jednostka'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('PRAWNIK', 'Radca prawny'), ('OBSLUGA', 'Pomoc administracyjna'), ('RADA', 'Zarząd Rady Dyscypliny')], max_length=50, null=True, verbose_name='Rola'),
        ),
    ]
