# Generated by Django 5.2 on 2025-05-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadaDyscypliny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa rady dyscypliny')),
            ],
            options={
                'verbose_name': 'Rada Dyscypliny',
                'verbose_name_plural': 'Rady Dyscypliny',
                'ordering': ['wydzial', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Wydzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True, verbose_name='Nazwa wydziału')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
                'ordering': ['nazwa'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='rada_wydzialu',
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Znacznik czasu')),
                ('action_type', models.CharField(choices=[('USER_CREATED', 'Utworzono użytkownika'), ('USER_UPDATED', 'Zaktualizowano użytkownika'), ('USER_DELETED', 'Usunięto użytkownika'), ('LOGIN_SUCCESS', 'Pomyślne logowanie'), ('LOGIN_FAILED', 'Nieudane logowanie'), ('PIN_SENT', 'Wysłano PIN 2FA'), ('PIN_VERIFIED', 'PIN 2FA zweryfikowany')], max_length=50, verbose_name='Typ akcji')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Szczegóły')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik wykonujący akcję')),
            ],
            options={
                'verbose_name': 'Wpis dziennika zdarzeń',
                'verbose_name_plural': 'Dziennik zdarzeń',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rada_dyscypliny_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.radadyscypliny', verbose_name='Rada Dyscypliny'),
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='wydzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rady_dyscypliny', to='users.wydzial', verbose_name='Wydział'),
        ),
        migrations.AddField(
            model_name='user',
            name='wydzial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.wydzial', verbose_name='Wydział'),
        ),
        migrations.AlterUniqueTogether(
            name='radadyscypliny',
            unique_together={('nazwa', 'wydzial')},
        ),
    ]
