# Generated by Django 5.2 on 2025-05-07 13:05

from django.db import migrations

def populate_data(apps, schema_editor):
    Wydzial = apps.get_model('users', 'Wydzial')
    RadaDyscypliny = apps.get_model('users', 'RadaDyscypliny')

    # Dane: Struktura Wydział -> [Lista Rad Dyscypliny]
    data = {
        "Wydział Budownictwa, Inżynierii Środowiska i Architektury": [
            "Rada Dyscypliny Architektura i Urbanistyka",
            "Rada Dyscypliny Inżynieria Lądowa, Geodezja i Transport",
            "Rada Dyscypliny Inżynieria Środowiska, Górnictwo i Energetyka",
        ],
        "Wydział Budowy Maszyn i Lotnictwa": [
            "Rada Dyscypliny Inżynieria Materiałowa", # Ta rada występuje też na Wydziale Mechaniczno-Technologicznym
            "Rada Dyscypliny Inżynieria Mechaniczna",  # Ta rada występuje też na Wydziale Mechaniczno-Technologicznym
        ],
        "Wydział Chemiczny": [
            "Rada Dyscypliny Inżynieria Chemiczna",
        ],
        "Wydział Elektrotechniki i Informatyki": [
            "Rada Dyscypliny Informatyka Techniczna i Telekomunikacja",
            "Rada Dyscypliny Automatyka, Elektronika, Elektrotechnika i Technologie Kosmiczne",
        ],
        "Wydział Matematyki i Fizyki Stosowanej": [
            "Rada Dyscypliny Matematyka",
            "Rada Dyscypliny Nauki Fizyczne",
        ],
        "Wydział Mechaniczno-Technologiczny": [
            "Rada Dyscypliny Inżynieria Mechaniczna", # Ta rada występuje też na Wydziale Budowy Maszyn i Lotnictwa
            "Rada Dyscypliny Inżynieria Materiałowa", # Ta rada występuje też na Wydziale Budowy Maszyn i Lotnictwa
        ],
        "Wydział Zarządzania": [
            "Rada dyscypliny nauki o zarządzaniu i jakości", # Małe litery - zachowuję jak podałeś
            "Rada dyscypliny nauki o bezpieczeństwie",     # Małe litery
            "Rada dyscypliny ekonomia i finanse",          # Małe litery
        ],
    }

    for nazwa_wydzialu, lista_rad in data.items():
        # Używamy get_or_create, aby uniknąć duplikatów, jeśli migracja byłaby uruchamiana wielokrotnie
        # chociaż dla migracji danych zwykle nie ma takiej potrzeby, to dobra praktyka.
        wydzial_obj, created_w = Wydzial.objects.get_or_create(nazwa=nazwa_wydzialu)
        if created_w:
            print(f"Utworzono wydział: {nazwa_wydzialu}")

        for nazwa_rady in lista_rad:
            # Dla rad używamy get_or_create w kontekście konkretnego wydziału,
            # co jest zgodne z unique_together = ('nazwa', 'wydzial') w modelu RadaDyscypliny.
            rada_obj, created_r = RadaDyscypliny.objects.get_or_create(
                nazwa=nazwa_rady,
                wydzial=wydzial_obj
            )
            if created_r:
                print(f"  Dodano radę: {nazwa_rady} do wydziału: {nazwa_wydzialu}")

def revert_populate_data(apps, schema_editor):
    # Ta funkcja jest opcjonalna, ale dobra praktyka, jeśli chcemy móc cofnąć migrację.
    # Usuwa tylko te dane, które zostały dodane przez tę migrację.
    # W prostym przypadku można by usunąć wszystkie obiekty, ale to ryzykowne.
    # Tutaj, dla bezpieczeństwa, możemy założyć, że jeśli chcemy cofnąć,
    # to usuwamy wszystko (lub bardziej złożona logika, jeśli to potrzebne).
    Wydzial = apps.get_model('users', 'Wydzial')
    RadaDyscypliny = apps.get_model('users', 'RadaDyscypliny')
    
    # Ostrożnie: to usunie WSZYSTKIE rady i wydziały.
    # Jeśli inne migracje też dodają dane, to nie jest idealne.
    # Dla tego konkretnego przypadku, jeśli to jedyne miejsce dodawania tych danych, może być OK.
    print("Usuwanie danych o radach dyscypliny...")
    RadaDyscypliny.objects.all().delete()
    print("Usuwanie danych o wydziałach...")
    Wydzial.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_radadyscypliny_wydzial_remove_user_rada_wydzialu_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=revert_populate_data),
    ]