# Generated by Django 5.2 on 2025-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_wydzialy_i_rady'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=255, verbose_name='Miasto')),
                ('kod_pocztowy', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('ulica', models.CharField(max_length=255, verbose_name='Ulica')),
                ('nr_budynku', models.CharField(max_length=20, verbose_name='Nr budynku/lokalu')),
                ('afiliacja_uczelnia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afiliacja - Uczelnia')),
                ('afiliacja_wydzial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afiliacja - Wydział')),
                ('afiliacja_jednostka', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afiliacja - Jednostka')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='Funkcja_czlonka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True, verbose_name='Nazwa funkcji')),
            ],
            options={
                'verbose_name': 'Funkcja członka (Rady/Komisji)',
                'verbose_name_plural': 'Funkcje członków (Rady/Komisji)',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True, verbose_name='Nazwa uprawnienia')),
            ],
            options={
                'verbose_name': 'Uprawnienie (wg schematu SQL)',
                'verbose_name_plural': 'Uprawnienia (wg schematu SQL)',
                'ordering': ['nazwa'],
            },
        ),
    ]
