# Generated by Django 5.2 on 2025-05-07 16:58

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    """Wypełnia modele Funkcja_czlonka i Uprawnienia podstawowymi danymi."""
    Funkcja_czlonka = apps.get_model('users', 'Funkcja_czlonka')
    Uprawnienia = apps.get_model('users', 'Uprawnienia')

    funkcje = [
        "przewodniczący",
        "wiceprzewodniczący",
        "sekretarz",
        "członek",
        # Można dodać inne, jeśli są potrzebne np. "członek komisji 8PRK" itp.
    ]

    uprawnienia_sql = [
        "root", # Uwaga: mapowanie na superużytkownika Django?
        "prawnik",
        "administracja", # Uwaga: mapowanie na rolę OBSLUGA?
        "przewodniczący", # Uwaga: czy to rola systemowa, czy funkcja w radzie? Powiązanie z SkladRD?
        "wiceprzewodniczący",
        "sekretarz",
        # Można dodać inne zdefiniowane w User.Role: 'ADMIN', 'RADA' jeśli mają odpowiadać
    ]

    print("\nDodawanie funkcji członków...")
    for nazwa_funkcji in funkcje:
        obj, created = Funkcja_czlonka.objects.get_or_create(nazwa=nazwa_funkcji)
        if created:
            print(f"  Dodano funkcję: {nazwa_funkcji}")

    print("\nDodawanie uprawnień (wg schematu SQL)...")
    for nazwa_uprawnienia in uprawnienia_sql:
        obj, created = Uprawnienia.objects.get_or_create(nazwa=nazwa_uprawnienia)
        if created:
            print(f"  Dodano uprawnienie: {nazwa_uprawnienia}")

def revert_initial_data(apps, schema_editor):
    """Usuwa dane dodane przez tę migrację."""
    Funkcja_czlonka = apps.get_model('users', 'Funkcja_czlonka')
    Uprawnienia = apps.get_model('users', 'Uprawnienia')

    # Nazwy dodane w tej migracji (aby uniknąć usuwania innych, jeśli byłyby dodane gdzie indziej)
    funkcje_to_delete = [ "przewodniczący", "wiceprzewodniczący", "sekretarz", "członek" ]
    uprawnienia_to_delete = [ "root", "prawnik", "administracja", "przewodniczący", "wiceprzewodniczący", "sekretarz" ]

    print("\nUsuwanie funkcji członków...")
    Funkcja_czlonka.objects.filter(nazwa__in=funkcje_to_delete).delete()
    print("\nUsuwanie uprawnień (wg schematu SQL)...")
    Uprawnienia.objects.filter(nazwa__in=uprawnienia_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adres_funkcja_czlonka_uprawnienia'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_code=revert_initial_data),
    ]