# Generated by Django 5.2 on 2025-05-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_populate_funkcje_i_uprawnienia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres_Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferowany', models.BooleanField(default=False, verbose_name='Adres preferowany/korespondencyjny')),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adres', verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Powiązanie Adres-Osoba',
                'verbose_name_plural': 'Powiązania Adres-Osoba',
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('tytul_stopien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tytuł/Stopień naukowy (przed nazwiskiem)')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adres email')),
                ('stanowisko', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stanowisko')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('link_do_profilu_nauka_polska', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do profilu Nauka Polska/ORCID itp.')),
                ('specjalnosci', models.TextField(blank=True, null=True, verbose_name='Specjalności naukowe')),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1, verbose_name='Płeć')),
                ('tytul_po', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tytuł/Stopień (po nazwisku)')),
                ('imie_nazwisko_dopelniacz', models.CharField(max_length=510, verbose_name='Dopełniacz (kogo, czego?)')),
                ('imie_nazwisko_celownik', models.CharField(max_length=510, verbose_name='Celownik (komu, czemu?)')),
                ('imie_nazwisko_biernik', models.CharField(max_length=510, verbose_name='Biernik (kogo, co?)')),
                ('adresy', models.ManyToManyField(through='users.Adres_Osoba', to='users.adres', verbose_name='Adresy')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.AddField(
            model_name='adres_osoba',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.osoba', verbose_name='Osoba'),
        ),
        migrations.AlterUniqueTogether(
            name='adres_osoba',
            unique_together={('osoba', 'adres')},
        ),
    ]
