# Generated by Django 5.2 on 2025-05-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adres_osoba_osoba_adres_osoba_osoba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkladRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_powolania', models.DateField(blank=True, null=True, verbose_name='Data powołania')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Członkostwo aktywne')),
                ('funkcja_czlonka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.funkcja_czlonka', verbose_name='Funkcja w Radzie')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.osoba', verbose_name='Osoba (Członek Rady)')),
                ('rd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklad', to='users.radadyscypliny', verbose_name='Rada Dyscypliny')),
            ],
            options={
                'verbose_name': 'Skład Rady Dyscypliny',
                'verbose_name_plural': 'Składy Rad Dyscyplin',
                'ordering': ['rd', 'osoba__nazwisko', 'osoba__imie'],
                'unique_together': {('rd', 'osoba')},
            },
        ),
    ]
