# Generated by Django 5.2 on 2025-05-08 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_skladrd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adres email')),
                ('tytul_stopien', models.CharField(max_length=255, verbose_name='Tytuł/Stopień naukowy')),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1, verbose_name='Płeć')),
                ('imie_nazwisko_dopelniacz', models.CharField(max_length=510, verbose_name='Dopełniacz (kogo, czego?)')),
                ('imie_nazwisko_celownik', models.CharField(max_length=510, verbose_name='Celownik (komu, czemu?)')),
                ('imie_nazwisko_biernik', models.CharField(max_length=510, verbose_name='Biernik (kogo, co?)')),
                ('adres_ulica', models.CharField(max_length=255, verbose_name='Ulica')),
                ('adres_kod_pocztowy', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('adres_miasto', models.CharField(max_length=255, verbose_name='Miasto')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Doktorant',
                'verbose_name_plural': 'Doktoranci',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='radadyscypliny',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='skladrd',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='adres_kod_pocztowy',
            field=models.CharField(default='', max_length=20, verbose_name='Kod pocztowy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='adres_miasto',
            field=models.CharField(default='', max_length=255, verbose_name='Miasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='adres_ulica',
            field=models.CharField(default='', max_length=255, verbose_name='Ulica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='Email rady'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='logo',
            field=models.CharField(default='', max_length=255, verbose_name='Ścieżka do logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='telefon',
            field=models.CharField(default='', max_length=50, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radadyscypliny',
            name='www_adres',
            field=models.URLField(default='', max_length=255, verbose_name='Adres WWW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wydzial',
            name='adres_kod_pocztowy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='wydzial',
            name='adres_miasto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='wydzial',
            name='adres_ulica',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulica'),
        ),
        migrations.AddField(
            model_name='wydzial',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email wydziału'),
        ),
        migrations.AddField(
            model_name='wydzial',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ścieżka do logo'),
        ),
        migrations.AddField(
            model_name='wydzial',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='wydzial',
            name='www_adres',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Adres WWW'),
        ),
        migrations.AlterField(
            model_name='uprawnienia',
            name='nazwa',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa uprawnienia (wg SQL)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adres email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rada_dyscypliny_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.radadyscypliny', verbose_name='Rada Dyscypliny (jeśli dotyczy)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wydzial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.wydzial', verbose_name='Wydział (jeśli dotyczy)'),
        ),
        migrations.AddConstraint(
            model_name='radadyscypliny',
            constraint=models.UniqueConstraint(fields=('nazwa', 'wydzial'), name='unique_rada_in_wydzial'),
        ),
        migrations.AddConstraint(
            model_name='skladrd',
            constraint=models.UniqueConstraint(fields=('rd', 'osoba'), name='unique_osoba_in_rd'),
        ),
        migrations.AddField(
            model_name='doktorant',
            name='rada_dyscypliny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doktoranci', to='users.radadyscypliny', verbose_name='Rada Dyscypliny'),
        ),
    ]
