# Generated by Django 5.2 on 2025-05-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_doktorant_alter_radadyscypliny_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'Utworzono użytkownika'), ('USER_UPDATED', 'Zaktualizowano użytkownika'), ('USER_DELETED', 'Usunięto użytkownika'), ('LOGIN_SUCCESS', 'Pomyślne logowanie'), ('LOGIN_FAILED', 'Nieudane logowanie'), ('PIN_SENT', 'Wysłano PIN 2FA'), ('PIN_VERIFIED', 'PIN 2FA zweryfikowany'), ('DOKTORANT_CREATED', 'Utworzono doktoranta'), ('DOKTORANT_UPDATED', 'Zaktualizowano doktoranta'), ('DOKTORANT_DELETED', 'Usunięto doktoranta')], max_length=50, verbose_name='Typ akcji'),
        ),
    ]
