# Generated by Django 5.2 on 2025-05-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=255, verbose_name='Miasto')),
                ('kod_pocztowy', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('ulica', models.CharField(max_length=255, verbose_name='Ulica')),
                ('nr_budynku', models.CharField(max_length=50, verbose_name='Nr budynku/lokalu')),
                ('afiliacja_uczelnia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afiliacja - Uczelnia')),
                ('afiliacja_wydzial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afiliacja - Wydział')),
                ('afiliacja_jednostka', models.CharField(blank=True, max_length=255, null=True, verbose_name='Afiliacja - Jednostka')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='FunkcjaCzlonka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True, verbose_name='Nazwa funkcji')),
            ],
            options={
                'verbose_name': 'Funkcja członka',
                'verbose_name_plural': 'Funkcje członków',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Wydzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True, verbose_name='Nazwa wydziału')),
                ('adres_ulica', models.CharField(max_length=255, verbose_name='Ulica')),
                ('adres_miasto', models.CharField(max_length=255, verbose_name='Miasto')),
                ('adres_kod_pocztowy', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email wydziału')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('logo', models.CharField(blank=True, max_length=255, verbose_name='Ścieżka/URL do logo')),
                ('www_adres', models.URLField(blank=True, max_length=255, verbose_name='Adres WWW')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='AdresOsoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferowany', models.BooleanField(default=False, verbose_name='Adres preferowany?')),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adres')),
            ],
            options={
                'verbose_name': 'Przypisanie adresu do osoby',
                'verbose_name_plural': 'Przypisania adresów do osób',
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('tytul_stopien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tytuł/Stopień naukowy')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('stanowisko', models.CharField(max_length=255, verbose_name='Stanowisko')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('link_do_profilu_gov', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do Profilu Nauka Polska/Gov')),
                ('specjalnosci', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specjalności')),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta'), ('I', 'Inna')], max_length=1, verbose_name='Płeć')),
                ('tytul_po', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tytuł po nazwisku (np. prof. ucz.)')),
                ('imie_nazwisko_dopelniacz', models.CharField(max_length=255, verbose_name='Imię Nazwisko (Dopełniacz)')),
                ('imie_nazwisko_celownik', models.CharField(max_length=255, verbose_name='Imię Nazwisko (Celownik)')),
                ('imie_nazwisko_biernik', models.CharField(max_length=255, verbose_name='Imię Nazwisko (Biernik)')),
                ('adresy', models.ManyToManyField(blank=True, through='core.AdresOsoba', to='core.adres', verbose_name='Adresy')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'ordering': ['nazwisko', 'imie'],
                'unique_together': {('imie', 'nazwisko', 'email')},
            },
        ),
        migrations.AddField(
            model_name='adresosoba',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.osoba'),
        ),
        migrations.CreateModel(
            name='RD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True, verbose_name='Nazwa rady')),
                ('adres_ulica', models.CharField(max_length=255, verbose_name='Ulica')),
                ('adres_kod_pocztowy', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('adres_miasto', models.CharField(max_length=255, verbose_name='Miasto')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=255, verbose_name='Email rady')),
                ('www_adres', models.URLField(max_length=255, verbose_name='Adres WWW')),
                ('logo', models.CharField(max_length=255, verbose_name='Ścieżka/URL do logo')),
                ('wydzial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rady_dyscyplin', to='core.wydzial', verbose_name='Wydział')),
            ],
            options={
                'verbose_name': 'Rada Dyscypliny',
                'verbose_name_plural': 'Rady Dyscyplin',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='adresosoba',
            unique_together={('osoba', 'adres')},
        ),
    ]
