# Generated by Django 5.2 on 2025-05-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzablonZdarzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(verbose_name='Opis szablonu zdarzenia')),
            ],
            options={
                'verbose_name': 'Szablon zdarzenia',
                'verbose_name_plural': 'Szablony zdarzeń',
                'ordering': ['opis'],
            },
        ),
        migrations.CreateModel(
            name='Doktorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tytuł rozprawy')),
                ('tryb', models.CharField(blank=True, choices=[('SZKOLA', 'Szkoła Doktorska'), ('EKSTERN', 'Tryb eksternistyczny')], max_length=10, null=True, verbose_name='Tryb studiów')),
                ('rozprawa', models.FileField(blank=True, max_length=255, null=True, upload_to='doktoraty/rozprawy/', verbose_name='Plik rozprawy')),
                ('komentarz', models.TextField(blank=True, null=True, verbose_name='Komentarz/Uwagi')),
                ('data_zlozenia_wniosku', models.DateField(blank=True, null=True, verbose_name='Data złożenia wniosku o wszczęcie')),
                ('uchwala_promotor_wszczecie_data', models.DateField(blank=True, null=True, verbose_name='Data uchwały (promotor/wszczęcie)')),
                ('uchwala_promotor_wszczecie_nr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nr uchwały (promotor/wszczęcie)')),
                ('data_obrony', models.DateField(blank=True, null=True, verbose_name='Data obrony')),
                ('uchwala_nadanie_stopnia_rd_data', models.DateField(blank=True, null=True, verbose_name='Data uchwały RD (nadanie stopnia)')),
                ('uchwala_nadanie_stopnia_rd_nr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nr uchwały RD (nadanie stopnia)')),
                ('wyroznienie', models.BooleanField(blank=True, null=True, verbose_name='Wyróżnienie?')),
                ('doktorant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='przewody_doktorskie', to='core.osoba', verbose_name='Doktorant')),
                ('kopromotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kopromotor_w_doktoratach', to='core.osoba', verbose_name='Kopromotor')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotor_w_doktoratach', to='core.osoba', verbose_name='Promotor')),
                ('promotor_pomocniczy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotor_pom_w_doktoratach', to='core.osoba', verbose_name='Promotor pomocniczy')),
                ('rada_dyscypliny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doktoraty', to='core.rd', verbose_name='Rada Dyscypliny')),
            ],
            options={
                'verbose_name': 'Przewód doktorski',
                'verbose_name_plural': 'Przewody doktorskie',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data zdarzenia')),
                ('opis', models.TextField(blank=True, null=True, verbose_name='Opis zdarzenia')),
                ('doktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='phd_process.doktorat', verbose_name='Doktorat')),
                ('szablon_zdarzenia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phd_process.szablonzdarzenia', verbose_name='Szablon zdarzenia')),
            ],
            options={
                'verbose_name': 'Wpis historii doktoratu',
                'verbose_name_plural': 'Historia doktoratów',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KomisjaDr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_powolania', models.DateField(blank=True, null=True, verbose_name='Data powołania')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny członek?')),
                ('czlonek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='w_komisjach', to='core.osoba', verbose_name='Członek komisji')),
                ('doktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='czlonkowie_komisji', to='phd_process.doktorat', verbose_name='Doktorat')),
                ('funkcja_czlonka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funkcjaczlonka', verbose_name='Funkcja w komisji')),
            ],
            options={
                'verbose_name': 'Członek komisji doktorskiej',
                'verbose_name_plural': 'Członkowie komisji doktorskich',
                'unique_together': {('doktorat', 'czlonek')},
            },
        ),
        migrations.CreateModel(
            name='Recenzent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny recenzent?')),
                ('recenzja', models.FileField(blank=True, max_length=255, null=True, upload_to='doktoraty/recenzje/', verbose_name='Plik recenzji')),
                ('data_przyjecia_rozprawy', models.DateField(blank=True, null=True, verbose_name='Data przyjęcia rozprawy przez recenzenta')),
                ('data_wykonania_recenzji', models.DateField(blank=True, null=True, verbose_name='Data wykonania recenzji')),
                ('wyroznienie', models.BooleanField(blank=True, null=True, verbose_name='Wyróżnienie recenzenta?')),
                ('doktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzenci', to='phd_process.doktorat', verbose_name='Doktorat')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recenzje', to='core.osoba', verbose_name='Recenzent')),
            ],
            options={
                'verbose_name': 'Recenzent',
                'verbose_name_plural': 'Recenzenci',
                'unique_together': {('doktorat', 'osoba')},
            },
        ),
        migrations.CreateModel(
            name='SkladRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_powolania', models.DateField(blank=True, null=True, verbose_name='Data powołania')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny w składzie?')),
                ('funkcja_czlonka_rd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funkcjaczlonka', verbose_name='Funkcja w Radzie')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_radach', to='core.osoba', verbose_name='Osoba')),
                ('rd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklad', to='core.rd', verbose_name='Rada Dyscypliny')),
            ],
            options={
                'verbose_name': 'Członek składu Rady Dyscypliny',
                'verbose_name_plural': 'Składy Rad Dyscyplin',
                'unique_together': {('rd', 'osoba')},
            },
        ),
    ]
