# Generated by Django 5.2 on 2025-05-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('phd_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzablonDokumentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(verbose_name='Opis szablonu')),
                ('tresc', models.FileField(blank=True, max_length=255, null=True, upload_to='dokumenty/szablony/', verbose_name='Plik szablonu (.tex, .docx?)')),
            ],
            options={
                'verbose_name': 'Szablon dokumentu',
                'verbose_name_plural': 'Szablony dokumentów',
            },
        ),
        migrations.CreateModel(
            name='DokumentWniosekUchwala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data dokumentu')),
                ('numer', models.CharField(max_length=255, verbose_name='Numer dokumentu')),
                ('plik_pdf', models.FileField(max_length=255, upload_to='dokumenty/wygenerowane/', verbose_name='Plik PDF')),
                ('kierunek', models.CharField(blank=True, choices=[('Wychodzący', 'Wychodzący'), ('Przychodzący', 'Przychodzący')], max_length=20, null=True, verbose_name='Kierunek (Wychodzący/Przychodzący)')),
                ('adresat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumenty_adresowane', to='core.osoba', verbose_name='Adresat')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumenty_autorskie', to='core.osoba', verbose_name='Autor')),
                ('wpis_historii', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powiazane_dokumenty', to='phd_process.historia', verbose_name='Powiązane zdarzenie historii')),
                ('szablon_uzyty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wygenerowane_dokumenty', to='documents.szablondokumentu', verbose_name='Użyty szablon')),
            ],
            options={
                'verbose_name': 'Dokument/Wniosek/Uchwała',
                'verbose_name_plural': 'Dokumenty/Wnioski/Uchwały',
                'ordering': ['-data'],
            },
        ),
    ]
