from django.contrib import admin
from django.urls import path, include
from users.views import (home, no_role, manage_users, system_settings, reports,
                         legal_docs, add_doc, archive_docs, view_requests,
                         handle_request, archive_requests, meeting_plan,
                         protocols, add_resolution, access_denied, export_data,
                         import_data, legal_requests, legal_history, schedule,
                         announcements, view_resolutions, archive_resolutions,
                         edit_user, delete_user, dashboard, news, catalog,
                         for_everyone)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', home, name='home'),
    path('no-role/', no_role, name='no_role'),
    path('access-denied/', access_denied, name='access_denied'),
    path('dashboard/', dashboard, name='dashboard'),
    path('news/', news, name='news'),
    path('catalog/', catalog, name='catalog'),
    path('for_everyone/', for_everyone, name='for_everyone'),
    path('manage_users/', manage_users, name='manage_users'),
    path('edit_user/<int:user_id>/', edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('system_settings/', system_settings, name='system_settings'),
    path('reports/', reports, name='reports'),
    path('legal_docs/', legal_docs, name='legal_docs'),
    path('add_doc/', add_doc, name='add_doc'),
    path('archive_docs/', archive_docs, name='archive_docs'),
    path('view_requests/', view_requests, name='view_requests'),
    path('handle_request/', handle_request, name='handle_request'),
    path('archive_requests/', archive_requests, name='archive_requests'),
    path('meeting_plan/', meeting_plan, name='meeting_plan'),
    path('protocols/', protocols, name='protocols'),
    path('add_resolution/', add_resolution, name='add_resolution'),
    path('export_data/', export_data, name='export_data'),
    path('import_data/', import_data, name='import_data'),
    path('legal_requests/', legal_requests, name='legal_requests'),
    path('legal_history/', legal_history, name='legal_history'),
    path('schedule/', schedule, name='schedule'),
    path('announcements/', announcements, name='announcements'),
    path('view_resolutions/', view_resolutions, name='view_resolutions'),
    path('archive_resolutions/', archive_resolutions, name='archive_resolutions'),
]